### ISSUE TITLE
Cache key on 5.2.0.rc1

### ISSUE THREAD

**Issue by arni1981** [redis-store/redis-activesupport#102]
### Steps to reproduce
`<% cache @group %>`

No longer includes the updated_at in the cache_key in 5.2.0.rc1

### Expected behavior
This is an example of a generated key in 5.2.0.beta2
`groups/show:b25ce2a718e61c4980803b1b01b4d28a/groups/3-20180219205350119722`

### Actual behavior
The same command in 5.2.0.rc1 does not include the updated_at and therefore is stale even though the record is updated
`groups/show:d8f81a8f744c2141d7eb53baca7d32fa/groups/3`

I have not enabled this line in the `initializers/new_framework_defaults_5_2.rb` file
`# Rails.application.config.active_record.cache_versioning = true`

**Comment by tubbo** [comment]
You shouldn’t need to enable that, on rails/rails@5-2-stable it would seem that setting is enabled by default. I’ll try to reproduce this in a test case.

**Comment by arni1981** [comment]
You either need to enable it in this file or add this to your `application.rb` file, which is done automatically on a new 5.2 application.

`config.load_defaults 5.2`

**Comment by tubbo** [comment]
With `config.load_defaults 5.2` in my **application.rb**, and `config.cache_store = :memory_store` in **config/environments/development.rb**, I don't get the `:updated_at` timestamp in my cache keys...

```
irb(main):002:0> Project.first.cache_key
  Project Load (0.5ms)  SELECT  "projects".* FROM "projects" ORDER BY "projects"."id" ASC LIMIT $1  [["LIMIT", 1]]
=> "projects/1"
```

I noticed you opened rails/rails#32061 as well, but you didn't test using the in-memory store, which I think would have prevented them flagging it as an issue. We should probably re-open that issue and deal with this from the perspective of `AS::Cache::Store`

**Comment by tubbo** [comment]
@arni1981 This looks like it's expected behavior, as cache invalidation now lives in the marshalled `AS::Cache::Entry` objects themselves due to the new "recyclable cache keys" feature. hence why you don't need `:updated_at` in the cache key anymore. I'm not entirely sure if **redis-activesupport** needs to/can do anything here.

**Comment by arni1981** [comment]
I don't know either, I just know that it doing the basic `- cache @product` doesn't work anymore on `redis_store` with 5.2.0.rc1, but works with both `mem_cache_store` and `memory_store`

**Comment by tubbo** [comment]
@arni1981 I was able to reproduce and got it working, turns out we were overriding `#write` and I don't believe it's necessary anymore. The fix is incoming. :)

**Comment by arni1981** [comment]
That's good to hear, I use `redis-store` a lot for caching.

**Comment by tubbo** [comment]
hey @arni1981 sorry you had to wait so long for this one, I just merged the fix...let me know if using the master branch of `redis-activesupport` works for you. I'd like this to receive extensive testing before we actually cut a release.

**Comment by arni1981** [comment]
@tubbo Hi, I tried it after putting this in my Gemfile, but I still get the cache key without the timestamp. It still works with `5.2.0.beta2` as before.

`gem 'redis-activesupport', github: 'redis-store/redis-activesupport'`

Do I need to update my `Gemfile` any further maybe to pull in some other branches?

**Comment by tubbo** [comment]
@arni1981 No, you're on the right branch. The cache key isn't supposed to include the timestamp information. Instead, the value is now wrapped in a marshalled `ActiveSupport::Cache::Entry`, which includes the `version` that is, I believe, set automatically to the `updated_at` timestamp of your model when you do e.g. `- cache @model do` in your view for example.

**Comment by arni1981** [comment]
@tubbo Ok, it still doesn't work, the page is stale as in the original problem description.

**Comment by tubbo** [comment]
hey @arni1981, we've dropped support for rails 5.2+ on redis-activespport...and recommend a switch to the built-in `:redis_cache_store` instead. 

https://github.com/redis-store/redis-activesupport#a-quick-note-about-rails-52

**Comment by arni1981** [comment]
Yes, I already did that. Thanks for the help and good luck with your project(s).
